class LocationData {
  static const String defaultProvince = 'Agusan del Sur';
  
  static const Map<String, List<String>> municipalityBarangays = {
    'Bayugan': [
      'Berseba',
      'Bucac',
      'Cagbas',
      'Calaitan',
      'Canayugan',
      'Charito',
      'Claro Cortez',
      'Fili',
      'Gamao',
      'Getsemane',
      'Grace Estate',
      'Hamogaway',
      'Katipunan',
      'Mabuhay',
      'Magkiangkang',
      'Mahayag',
      'Marcelina',
      'Maygatasan',
      'Montivesta',
      'Mt. Ararat',
      'Mt. Carmel',
      'Mt. Olive',
      'New Salem',
      'Noli',
      'Osmeña',
      'Panaytay',
      'Pinagalaan',
      'Poblacion',
      'Sagmone',
      'Saguma',
      'Salvacion',
      'San Agustin',
      'San Isidro',
      'San Juan',
      'Santa Irene',
      'Santa Teresita',
      'Santo Niño',
      'Taglatawan',
      'Taglibas',
      'Tagubay',
      'Verdu',
      'Villa Undayon',
      'Wawa',
    ],
    'Bunawan': [
      'Brook',
      'Consuelo',
      'Imelda',
      'Libertad',
      'Mambalili',
      'Nueva Era',
      'Poblacion',
      'San Andres',
      'San Marcos',
      'San Teodoro',
    ],
    'Esperanza': [
      'Agsabu',
      'Aguinaldo',
      'Anolingan',
      'Bakingking',
      'Balubo',
      'Bentahon',
      'Bunaguit',
      'Catmonon',
      'Cebulan',
      'Concordia',
      'Crossing Luna',
      'Cubo',
      'Dakutan',
      'Duangan',
      'Guadalupe',
      'Guibonon',
      'Hawilian',
      'Kalabuan',
      'Kinamaybay',
      'Labao',
      'Langag',
      'Maasin',
      'Mac-Arthur',
      'Mahagcot',
      'Maliwanag',
      'Milagros',
      'Nato',
      'New Gingoog',
      'Odiong',
      'Oro',
      'Piglawigan',
      'Poblacion',
      'Remedios',
      'Salug',
      'San Isidro',
      'San Jose',
      'San Toribio',
      'San Vicente',
      'Santa Fe',
      'Segunda',
      'Sinakungan',
      'Tagabase',
      'Taganahaw',
      'Tagbalili',
      'Tahina',
      'Tandang Sora',
      'Valentina',
    ],
    'La Paz': [
      'Angeles',
      'Bataan',
      'Comota',
      'Halapitan',
      'Kasapa II',
      'Langasian',
      'Lydia',
      'Osmeña, Sr.',
      'Panagangan',
      'Poblacion',
      'Sabang Adgawan',
      'Sagunto',
      'San Patricio',
      'Valentina',
      'Villa Paz',
    ],
    'Loreto': [
      'Binucayan',
      'Johnson',
      'Kasapa',
      'Katipunan',
      'Kauswagan',
      'Magaud',
      'Nueva Gracia',
      'Poblacion',
      'Sabud',
      'San Isidro',
      'San Mariano',
      'San Vicente',
      'Santa Teresa',
      'Santo Niño',
      'Santo Tomas',
      'Violanta',
      'Waloe',
    ],
    'Patin-ay': [
      'Poblacion (Bahbah)',
      'Salimbogaon',
      'Salvacion',
      'San Joaquin',
      'San Jose',
      'San Lorenzo',
      'San Martin',
      'San Pedro',
      'San Rafael',
      'San Roque',
      'San Salvador',
      'San Vicente',
      'Santa Irene',
      'Santa Maria',
    ],
    'Prosperidad': [
      'Aurora',
      'Awa',
      'Azpetia',
      'La Caridad',
      'La Perian',
      'La Purisima',
      'La Suerte',
      'La Union',
      'Las Navas',
      'Libertad',
      'Los Arcos',
      'Lucena',
      'Mabuhay',
      'Magsaysay',
      'Mapaga',
      'Napo',
      'New Maug',
    ],
    'Rosario': [
      'Bayugan 3',
      'Cabantao',
      'Cabawan',
      'Libuac',
      'Maligaya',
      'Marfil',
      'Novele',
      'Poblacion',
      'Santa Cruz',
      'Tagbayagan',
      'Wasi-an',
    ],
    'San Francisco': [
      'Alegria',
      'Barangay 1 (Poblacion)',
      'Barangay 2 (Poblacion)',
      'Barangay 3 (Poblacion)',
      'Barangay 4 (Poblacion)',
      'Barangay 5 (Poblacion)',
      'Bayugan 2',
      'Bitan-agan',
      'Borbon',
      'Buenasuerte',
      'Caimpugan',
      'Das-agan',
      'Ebro',
      'Hubang',
      'Karaus',
      'Lapinigan',
      'Lucac',
      'Mate',
      'New Visayas',
      'Ormaca',
      'Pasta',
      'Pisa-an',
      'Rizal',
      'San Isidro',
      'Santa Ana',
      'Tagapua',
    ],
    'San Luis': [
      'Anislagan',
      'Balit',
      'Baylo',
      'Binicalan',
      'Cecilia',
      'Coalicion',
      'Culi',
      'Dimasalang',
      'Don Alejandro',
      'Don Pedro',
      'Doña Flavia',
      'Doña Maxima',
      'Mahagsay',
      'Mahapag',
      'Mahayahay',
      'Muritula',
      'Nuevo Trabajo',
      'Poblacion',
      'Policarpo',
      'San Isidro',
      'San Pedro',
      'Santa Ines',
      'Santa Rita',
      'Santiago',
      'Wegguam',
    ],
    'Santa Josefa': [
      'Angas',
      'Aurora',
      'Awao',
      'Concepcion',
      'Pag-asa',
      'Patrocinio',
      'Poblacion',
      'San Jose',
      'Santa Isabel',
      'Sayon',
      'Tapaz',
    ],
    'Sibagat': [
      'Afga',
      'Anahawan',
      'Banagbanag',
      'Del Rosario',
      'El Rio',
      'Ilihan',
      'Kauswagan',
      'Kioya',
      'Kolambugan',
      'Magkalape',
      'Magsaysay',
      'Mahayahay',
      'New Tubigon',
      'Padiay',
      'Perez',
      'Poblacion',
      'San Isidro',
      'San Vicente',
      'Santa Cruz',
      'Santa Maria',
      'Sinai',
      'Tabon-tabon',
      'Tag-uyango',
      'Villangit',
    ],
    'Talacogon': [
      'Batucan',
      'BuenaGracia',
      'Causwagan',
      'Culi',
      'Del Monte',
      'Desamparados',
      'La Flora',
      'Labnig',
      'Maharlika',
      'Marbon',
      'Sabang Gibung',
      'San Agustin (Poblacion)',
      'San Isidro (Poblacion)',
      'San Nicolas (Poblacion)',
      'Zamora',
      'Zillovia',
    ],
    'Trento': [
      'Basa',
      'Cebolin',
      'Cuevas',
      'Kapatungan',
      'Langkila-an',
      'Manat',
      'New Visayas',
      'Pangyan',
      'Poblacion',
      'Pulang-lupa',
      'Salvacion',
      'San Ignacio',
      'San Isidro',
      'San Roque',
      'Santa Maria',
      'Tudela',
    ],
    'Veruela': [
      'Anitap',
      'Bacay II',
      'Binongan',
      'Caigangan',
      'Candiis',
      'Del Monte',
      'Don Mateo',
      'Katipunan',
      'La Fortuna',
      'Limot',
      'Magsaysay',
      'Masayan',
      'Poblacion',
      'Sampaguita',
      'San Gabriel',
      'Santa Cruz',
      'Santa Emelia',
      'Sawagan',
      'Sinobong',
      'Sisimon',
    ],
  };
  
  static List<String> get municipalities => municipalityBarangays.keys.toList()..sort();
  
  static List<String> getBarangaysForMunicipality(String municipality) {
    return municipalityBarangays[municipality] ?? [];
  }
  
  static bool isValidMunicipality(String municipality) {
    return municipalityBarangays.containsKey(municipality);
  }
  
  static bool isValidBarangay(String municipality, String barangay) {
    return getBarangaysForMunicipality(municipality).contains(barangay);
  }
}